POST http://localhost:8080/api/users/load HTTP/1.1
content-type: application/json

{
"name":"Winta",
"teamName":"Holy",
"salary":"123456"
}
###
http://localhost:8080/api/users/all
###
http://localhost:8080/api/rest/usercontact
###
http://localhost:8080/api/rest/update/Winta
Andrew Mead’@22